title: Ran XIN # your name (or website title) here
logo: "./images/MyPhoto.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate student in City Planning with concentration in Smart Cities | UPenn
  <br><br>
  One thing I am most proud of myself: Lost 33 lbs in 1 year through persistent physical exerice and healthful diet 
  <br><br>
  Email: njxinran@design.upenn.edu
  <br><br>
  <a href="https://www.linkedin.com/in/ran-xin-chn95">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

